### ISSUE TITLE
what is the better alternative

### ISSUE THREAD

**Issue by endigma** [msteen/nixos-vsliveshare#11]
why did you write that without writing what it is

**Comment by zarelit** [comment]
This project was useful because for some time the liveshare extension was not packaged / was broken in the `nixpkgs` repository. Now liveshare works fine and is packaged so you can use `vscode-with-extensions` as explained here: https://nixos.wiki/wiki/Visual_Studio_Code . The liveshare extension is called (you can find the name from the marketplace) `ms-vsliveshare.vsliveshare`.
One thing that is  not mentioned, at least not at the time I've installed it, is that you must have gnome-keyring for it to work

**Comment by endigma** [comment]
thanks
