### ISSUE TITLE
Home-manager: not yet working.

### ISSUE THREAD

**Issue by phryneas** [msteen/nixos-vsliveshare#3]
To get it to install, I had to change in 
`home.nix`:
```diff
    Service = {
-      ExecStart = script;
+      ExecStart = "${script}";
    };
```

Then it installs, but it won't run for me - I'm not really sure what's happening there:

> % fix-vsliveshare
warning: ignoring the user-specified setting 'allow-unsafe-native-code-during-evaluation', because it is a restricted setting and you are not a trusted user
error: anonymous function at /nix/store/ly6najr545milxsnnnzazriyybv4msc0-vsliveshare/default.nix:2:1 called without required argument 'dotnet-sdk_3', at /nix/store/154m4w6grys1kca27gyr3fh8mjpd01jc-nixos-19.09.2079.8731aaaf8b3/nixos/lib/customisation.nix:69:12
Failed to build VS Code Live Share version '1.0.1711'.

**Comment by ottidmes** [comment]
Thank you for reporting! I will update the configuration to your suggestion. The first error is due to the use of `nix-prefetch`, I will add it to my TODO to see if I can fix that for `nix-prefetch`, for now I will see if I can use `nix-prefetch-url` instead. The `called without required argument 'dotnet-sdk_3'` is due to being on `nixos-19.09` or below, I will make this more obvious in the README, but there is an option available to workaround this shown in the README code fragment for installation under NixOS (rather than home-manager).

**Comment by msteen** [comment]
I have replaced `nix-prefetch` with `nix-prefetch-url`, fixed the home-manager service according to your suggestion, and updated the README to clarify the issue of needing .NET Core SDK 3. Could you try to see whether it now works out for you?

**Comment by phryneas** [comment]
It seems so successfully install the extension now. Still cannot sign in but I believe that might a problem on the github oauth redirection side right now, so probably not a problem with this project. Gonna close this for now, thank you!

**Comment by msteen** [comment]
I have only done limited testing myself with actually using it. I authorized it through my Microsoft account instead and then tried to connect to myself as a guest and that worked fine. If there is still something amiss though, don't hesitate to create another issue.
