### ISSUE TITLE
Did this break recently?

### ISSUE THREAD

**Issue by Avaq** [msteen/nixos-vsliveshare#8]
Thank you for this script, it's been of great help up until this point. :)
I'm running into an issue and maybe you know more.

My VSCode Liveshare stopped working a few days ago. I made sure to:

- Update nixos-vsliveshare
- Rerun `fix-vsliveshare`
- Reinstall the Livehsare plugin

One of these things sure did the trick before, but doesn't now.
Now when I press the "Share" or "Join" buttons, nothing happens.

**Comment by Avaq** [comment]
I just got it to work again by downgrading, as described in the README, to version 1.0.3784. I was not able to get it to work on either 1.0.3912 or 1.0.3968.

**Comment by msteen** [comment]
Thanks for reporting! This issue (I believe) has been fixed in a sort of fork of this project that does not require some of patching I am doing:
https://github.com/NixOS/nixpkgs/issues/41189#issuecomment-792395410

I will see this weekend if I should just end this project in favor of the above, or whether mine still has some use (will have to do some tests to determine that).

**Comment by Avaq** [comment]
Oh, thanks for the link! That certainly looks interesting. I'll try it out, if nixos-vsliveshare works better for me for whatever reason I'll let you know! :)

**Comment by Avaq** [comment]
This new approach works perfectly for me. I got a working version of 1.0.3912. Thank you again for providing nixos-vsliveshare for as long as it was needed. :)
